Feat/cli
RIT-MDRC/Catbot pull request #14
Opened 2023-10-11 17:38 UTC by hiromon0125

# Features
* Failed to add Arduino-Cli integration due to incompatibility with RaspberryPi and Arduino-Cli
* Add clear direction on how to set up Arduino extension in VSCode
* Setup arduino.json
* Setup gitignore
* Add sample blink code
* Set up repository to follow basic community standard
   - Add Code of conduct
   - Add Contributing
   - Add Security Policy
   - Add Pull Request Template
   - Add Issue Template

# How to Test
* Follow the directions on the ReadMe file and make sure all of the steps are clearly written
* Check to see if there are any errors in the main .ino file
* Make sure the main .ino file passes the verification of the Arduino extension

2023-10-20 04:05 UTC, cvr8924 approved these changes
Looks good to me. Only major thing I have is we may wanna document somewhere what is isn't functional / in progress. Approved regardless tho

2023-10-20 04:05 UTC, cvr8924 commented on .github/pull_request_template.md
> +# Feature
Not a critique but what is the purpose of this file. is the intention that a Pull Request file will be included in future PRs or is this just the template for PR descriptions in git. Similar question with Bug Reports. Those are currently managed through trello, is there an in git methodology you'd wanna use for them? i'm not opposed if their is im just unfamiliar

2023-10-20 04:05 UTC, cvr8924 commented on CODE_OF_CONDUCT.md
> +### 1. Correction
I mean realistically this codebase is administered under MDRC bylaws which would have its own reprimand process as an RIT club

2023-10-20 04:05 UTC, cvr8924 commented on README.md
> +* install [C/C++ extention](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) for VSCode
thank you for adding this its always so annoying when readme dependancies aren't accurate and its v/ easy to forger

2023-10-20 04:05 UTC, cvr8924 commented on README.md
> +* Example: `"includePath": ["${workspaceFolder}/**", "/Users/doofenshmirtz/Library/Arduino15/packages/arduino/hardware/mbed_nano/4.0.8/cores/arduino/mbed/**"]`
"doofenshmirtz"
 lol

2023-10-20 04:05 UTC, cvr8924 commented on cli/index.js
>  #! /usr/bin/env node
may be worth notating if this code is not currently in use / not functional just for posterity's sake.

2023-10-21 07:35 UTC, hiromon0125 commented on .github/pull_request_template.md
> +# Feature
The purpose of this file is for when the user is making a pr this template is suggested automatically and is given to the developers. It sets a basic template of what a good pr should have.

2023-10-21 07:36 UTC, hiromon0125 commented on .github/pull_request_template.md
> +# Feature
The template has two main things that every pr should contain: features description and direction to test the pr's feature. This makes it easy to test pr.

2023-10-21 07:38 UTC, hiromon0125 commented on cli/index.js
>  #! /usr/bin/env node
index is being used and can be used. install.js however is not and will be deprecated in the future is no proof of concept is made

2023-10-21 07:50 UTC, hiromon0125 commented on cli/index.js
>  #! /usr/bin/env node
running `npm -g install` and running `cb start` will run the main python program.

2023-10-21 08:00 UTC, hiromon0125 commented
code of conduct, README file, and cli README file has been updated to current code.

2023-10-27 01:07 UTC, thatnoobles requested changes
With the introduction of the CLI v2, it look like a lot of this becomes obsolete. Can we just merge that one instead?

2023-10-27 01:07 UTC, thatnoobles commented on README.md
> +* and make sure the code passes verification
Is this outdated?

2023-11-02 23:08 UTC, closed without merging