Feat/cli v2
RIT-MDRC/Catbot pull request #18
Opened 2023-10-23 19:55 UTC by hiromon0125

# Feature
* catbot cli v2
* postinstaller 
   - Creates a globally runnable folder that can be executed by any user
   - This is beneficial because only the devs needs to run the install command and the other users will automatically have up to date code

# How to Test
* ssh into catbot
* cd into the repo
* run `sudo npm -g install`
* run `su - catbotuser`
* run `catbot start`
* Check that the up to date script is written

2023-10-27 01:47 UTC, thatnoobles requested changes
I ran some of the commands and they seem to work fine, other than the Arduino one which should either be fixed or removed. Otherwise it looks fine, I hope I didn't miss anything but there are a lot of library files to sift through

2023-10-27 01:47 UTC, thatnoobles commented on cli/README.md
> +Refaced arduino-cli
`catbot a` and `catbot arduino` do not work; they throw a node error

2023-10-27 01:48 UTC, thatnoobles approved these changes
Didn't notice that you deleted the Arduino command since I started my review

2023-10-28 20:16 UTC, cvr8924 approved these changes
Honestly I want the Code of conduct gone but other then that I have very little objection not mentioned in a prior PR

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +
```suggestion
Project Leads, developers, and the board members in the club are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Project leads, project developers, and the club board members have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +representative at an online or offline event.
```suggestion
This Code of Conduct applies within all club spaces, and also applies when
an individual is officially representing the club and projects in public spaces.
Examples of representing our club and projects include using an official e-mail address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.
```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +reporter of any incident.
```suggestion
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported to the project leaders, the club board members, and the RIT officials responsible.

All members of the project and the club are obligated to respect the privacy and security of the
reporter of any incident.
```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +
```suggestion
Project leaders and club board members will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct:

```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +behavior was inappropriate. A public apology may be requested.
```suggestion

**Community Impact**: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the club space.

**Consequence**: A private, warning from project leaders, providing
clarity around the nature of the violation and an explanation of why the
behavior was inappropriate. A public apology may be requested.
```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +permanent ban.
```suggestion
**Consequence**: A warning with consequences for continued behavior. No
interaction with the people involved, including unsolicited interaction with
those enforcing the Code of Conduct, for a specified period of time. This
includes avoiding interactions in club spaces as well as external channels
like social media. Violating these terms may lead to a temporary or
permanent ban.
```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +Violating these terms may lead to a permanent ban.
```suggestion
**Community Impact**: A serious violation of community standards, including
sustained inappropriate behavior.

**Consequence**: A temporary ban from any sort of interaction or public
communication with the club for a specified period of time. No public or
private interaction with the people involved, including unsolicited interaction
with those enforcing the Code of Conduct, is allowed during this period.
Violating these terms may lead to a permanent ban.
```

2023-11-02 23:01 UTC, hiromon0125 commented on CODE_OF_CONDUCT.md
> +and the university may take their own actions.
```suggestion
**Community Impact**: Demonstrating a pattern of violation of community
standards, including sustained inappropriate behavior,  harassment of an
individual, or aggression toward or disparagement of classes of individuals.

**Consequence**: A permanent ban from any sort of public interaction within
the club. If deemed necessary the university official will be notified
and the university may take their own actions. 
```

2023-11-02 23:08 UTC, merged