Potentiometer (C++)
RIT-MDRC/Catbot pull request #24
Opened 2024-03-01 00:30 UTC by thatnoobles

Library code to read potentiometer values.

Communicates with potentiometers through Catbot's 12-bit ADC, and assumes that the ADC sits at I2C address `0x43` and reads from bus 1. Currently supports 8 connected potentiometers.

_(more information is viewable at the ADC's [datasheet](https://www.ti.com/lit/ds/symlink/ads7828.pdf), relevant content starts at page 11)_

2024-03-14 03:26 UTC, hiromon0125 requested changes
The code looks good to me just a few minor edits. 

5 questions/issues/concerns:
1. This potentiometer only allows for one i2C line for the entire group of potentiometers. 
2. Limitation on Parallelism architecture? Read multiple pots simultaneously?
3. Closing of I2C line? Who handles them? The OS? Python? or the compiled code?
4. The Potentiometer class has one function and an initializer. I have a feeling this is just an increase in complexity for no good reason. Also, know that you are going to have to write a single-line Python method that calls this function in Python and a dedicated initializer/parser method. What is the benefit of this class in C++ that it is inherently better to have it in cpp?
5. This might be more related toward the entire cpp source code organization as a whole, but the Python file structure is separated into components for import syntax purposes. I was wondering if cpp code could also follow a similar structure and have each cpp class live directly next to the python file that uses the class. It might be easier to find the cpp class definition from the Python script if it is organized that way. This will get rid of the Python and cpp directories, and makefile also does not have much of an issue either since you are pointing to each cpp file that needs to be compiled. Less difficulty navigating through differently organized folders might be worth investigating?
Let me know your thoughts

2024-03-14 03:26 UTC, hiromon0125 commented on .log/2024-03-04.18:16:02.debug.log
> +main.py: Initializing...
I think this shouldn't be comitted

2024-03-14 03:26 UTC, hiromon0125 commented on .vscode/settings.json
> +  "git.ignoreLimitWarning": true
remove this since you already have the library committed

2024-03-14 03:26 UTC, hiromon0125 commented on src/raspi/cpp/hello.cpp
> +#include <boost/python.hpp>
remove this before making the PR official

2024-03-14 03:26 UTC, hiromon0125 commented on src/raspi/cpp/io_controller/potentiometer.cpp
> +    uint8_t commandByte = (CHANNEL_SELECTION_MSB[index] << 4) + 0b1100;
```suggestion
    uint8_t commandByte = CHANNEL_SELECTION_MSB[index] << 4;
    commandByte |=  0b1100
```

2024-03-14 03:26 UTC, hiromon0125 commented on src/raspi/cpp/io_controller/potentiometer.h
> +        const uint8_t CHANNEL_SELECTION_MSB[8] = {
```suggestion
        const uint8_t CHANNEL_TO_ADDR_MAP[8] = {
```
Use more recognizable name

2024-03-14 03:26 UTC, hiromon0125 commented on src/raspi/cpp/io_controller/potentiometer.h
> +        const uint8_t CHANNEL_SELECTION_MSB[8] = {
also additionally add a comment that mentions using index as channel number and stores addresses as lists.

2024-03-14 03:26 UTC, hiromon0125 commented on test.py
> +from smbus2 import SMBus
Remember to move this file to a better location. Samples folder should be sufficient.

2024-03-21 23:13 UTC, thatnoobles commented on .vscode/settings.json
> +  "git.ignoreLimitWarning": true
gitignoring the whole .vscode directory since that should all be set up locally anyway

2024-03-21 23:16 UTC, thatnoobles commented on src/raspi/cpp/io_controller/potentiometer.cpp
> +    uint8_t commandByte = (CHANNEL_SELECTION_MSB[index] << 4) + 0b1100;
I've changed this to a binary OR (`|`) to more clearly what's happening here, but I don't really see the purpose of splitting this up

2024-03-21 23:53 UTC, thatnoobles commented
@hiromon0125

1. I've made a commit that stores ADC handles/addresses as arrays, and each potentiometer is initialized with an ADC index that associates it with a specific item in each array. In theory we could add more ADCs to the robot by adding more entries to these arrays.
2. Parallelism is limited by hardware. We only have one I2C bus, so we can only do one read/write operation on the bus at a time. However, I2C is fast enough where we can poll potentiometers in sequence and it will be _basically_ simultaneous.
3. To my knowledge--and from what I've seen--the I2C line is closed when the software is killed, since the process is no longer using it. If this ends up causing issues then we can add some simple cleanup code.
4. Performance, mostly. Even though the C++ code will only be run as fast as the Python code can call it, this does narrow down any performance issues to our Python code. Plus being able to enforce variable sizes (e.g. being able to deal in bytes) is nice.
5. Sure, makes sense :+1:

2024-03-23 22:36 UTC, hiromon0125 commented
> 1. I've made a commit that stores ADC handles/addresses as arrays, and each potentiometer is initialized with an ADC index that associates it with a specific item in each array. In theory, we could add more ADCs to the robot by adding more entries to these arrays.

Okay. Sounds good. I will take a look once you guys make it out of draft.

> 2. Parallelism is limited by hardware. We only have one I2C bus, so we can only do one read/write operation on the bus at a time. However, I2C is fast enough that we can poll potentiometers in sequence and it will be _basically_ simultaneous.

Yeah, I just want this class to be parallelism-safe such that anything we end up doing at the behavior level, we don't need to come back and change this. This idea has been incorporated in Python too therefore I want you guys to follow this as well.

> 3. To my knowledge--and from what I've seen--the I2C line is closed when the software is killed, since the process is no longer using it. If this ends up causing issues then we can add some simple cleanup code.

I want this for good practice. Python architecture is adding this in the next PR for I2C, so I want you guys to do this as well.

> 4. Performance, mostly. Even though the C++ code will only be run as fast as the Python code can call it, this does narrow down any performance issues to our Python code. Plus being able to enforce variable sizes (e.g. being able to deal in bytes) is nice.

I don't want to make the system complex from early on for "performance". This could bite us overall like how we already are falling behind schedule. 
I don't see how being able to deal with bytes in C code is different from Python. I just threw your code into ChatGPT and made it translate to Python and it threw out the same syntax. If "being able to deal in bytes" is just a bit shifting operation then this is not worth it because Python can do this as well. I also worry about memory manipulation and open any future developer to unsafe code practices. Reshaping the software architecture to prevent such a situation from early on will greatly improve our future developers, and we need to make sure this is one of our priorities. 

I am also mostly concerned about how much time this is taking you guys to complete. If hardware is the reason for the delay then software needs to adapt in such a way that we can develop independently from hardware; I told Danny to make this a priority. If the only way you guys can test the code is directly on the hardware, then you are also making the test susceptible to hardware issues, meaning you are testing the part you developed while also testing something you don't need to test.
I like you guys to make this PR out of the draft phase by the end of next Thursday's meeting. I would also like you guys to work on Documentation for this, and what ideas have been applied to solve any problems we might face in the future. While I did agree to let you guys develop some C code, if there is no over arching benefit from developing in C then we can not let this code into main branch. I will have a system for counting timer in Python soon and we can compare whether this C code is really more performant or it is just being a distraction. I also do not want any excuse that python program is slowing down your performance because ultimately we are weighing the portion of code you developed and comparing the section you have developed seeing if they are worth investing our time. I also want to incorporate development time in this as well so if something that takes three developers to develop in half a semester can be achieved by one developer in 2 weeks then that is a huge down side. 

I will also not going to approve a draft, so I need you guys to make this PR official before I make the next review.

2024-04-11 22:44 UTC, closed without merging